# Generated by Django 2.1.4 on 2018-12-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='testing',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
